### ISSUE TITLE
Better usage of the gradient highlight

### ISSUE THREAD

**Issue by jcs090218** [jcs090218/sHierarchy#18]
I have created the effect like what `Rainbow Hierarchy` achieved. In `Rainbow Hierarchy`, you could pick a color to have a nice looking gradient highlighting on items.

Since doing this would pollute the project itself (it would have generate some code to record the state of each scenes), I am think another way to make this a useful feature. Or maybe completely remove this?

@Matthew-T Any suggestions?

**Comment by jcs090218** [comment]
How about highlight with `tag` and `layer`? Would it be too messy?

**Comment by Matthew-T** [comment]
I don't know. I don't think I would ever use that feature.

**Comment by jcs090218** [comment]
Okay, I will close this for now! Thanks for your voice!
