### ISSUE TITLE
New name for this plugin

### ISSUE THREAD

**Issue by jcs090218** [jcs090218/sHierarchy#6]
cc @Matthew-T

**Comment by jcs090218** [comment]
How about `Utreenity`? Is `U` + `tree` + `nity`. Basically hierarchy is a treeview of the game objects corresponding to the scene container. And if you combine `U` and `nity` is `Unity`.

**Comment by Matthew-T** [comment]
Noooooo

**Comment by jcs090218** [comment]
@Matthew-T Any idea?

**Comment by Matthew-T** [comment]
Can't think of anything. But the name dosen't have to be complicated. It's a tool, so something basic that gives an idea of what it is used for.

**Comment by jcs090218** [comment]
This seems to be unnecessary. Close this now! :)
